-- Economics Theme 1 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.1.1', 'Economics as a Social Science', 'Economics is the study of how to allocate scarce resources among competing uses. As a social science, it uses the scientific method to build and test models of human behaviour. Key concepts include: positive statements (facts that can be tested), normative statements (value judgments), and the distinction between microeconomics and macroeconomics.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.1.2', 'The Nature and Purpose of Economic Activity', 'Economic activity involves the production, distribution, and consumption of goods and services. The fundamental economic problem is scarcity - unlimited wants but limited resources. This leads to the need for choice and the concept of opportunity cost (the next best alternative forgone).'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.1.3', 'Economic Resources', 'The four factors of production are: Land (natural resources), Labour (human effort), Capital (man-made aids to production), and Enterprise (risk-taking and organization). Each factor receives a reward: rent, wages, interest, and profit respectively.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.1.4', 'Scarcity, Choice and the Allocation of Resources', 'Scarcity necessitates choice. Resources can be allocated through: market mechanism (price signals), command/planned economy (government control), or mixed economy (combination). The Production Possibility Frontier (PPF) illustrates opportunity cost and trade-offs.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.1', 'Rational Decision Making', 'Economic agents (consumers, producers, government) are assumed to act rationally to maximize utility or profit. However, behavioral economics shows that people often deviate from rational behavior due to biases, bounded rationality, and imperfect information.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.2', 'Demand', 'Demand is the quantity of a good/service consumers are willing and able to buy at given prices over time. The law of demand states that as price rises, quantity demanded falls (inverse relationship). Demand curves slope downward. Factors affecting demand include: price, income, prices of substitutes/complements, tastes, population, and expectations.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.3', 'Price, Income and Cross Elasticities of Demand', 'Price Elasticity of Demand (PED) measures responsiveness of quantity demanded to price changes. Values: elastic (>1), inelastic (<1), unitary (=1). Income Elasticity (YED) measures response to income changes: normal goods (positive), inferior goods (negative). Cross Elasticity (XED) measures response to changes in prices of other goods: substitutes (positive), complements (negative).'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.4', 'Supply', 'Supply is the quantity producers are willing and able to produce at given prices over time. The law of supply states that as price rises, quantity supplied increases (positive relationship). Supply curves slope upward. Factors affecting supply include: price, costs of production, technology, taxes/subsidies, prices of other goods, expectations, and number of firms.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.5', 'Elasticity of Supply', 'Price Elasticity of Supply (PES) measures responsiveness of quantity supplied to price changes. Elastic supply (PES>1) occurs when firms can easily change production. Inelastic supply (PES<1) occurs when production is difficult to change. Factors affecting PES: spare capacity, stocks, time period, factor mobility.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.6', 'Price Determination', 'Market equilibrium occurs where demand equals supply. At equilibrium price, there is no shortage or surplus. Price mechanism functions: rationing (allocating scarce resources), signaling (information to producers/consumers), and incentive (motivation for resource allocation). Changes in demand/supply cause price and quantity to adjust to new equilibrium.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.2.7', 'Price Mechanism', 'The price mechanism allocates resources through: rationing function (prices ration scarce resources), signaling function (prices provide information), incentive function (prices create incentives for producers/consumers). Adam Smith''s "invisible hand" describes how self-interest leads to efficient resource allocation in free markets.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.3.1', 'Types of Market Failure', 'Market failure occurs when free markets fail to allocate resources efficiently. Types include: externalities (positive/negative), under-provision of public goods, information gaps/asymmetric information, monopoly power, and inequality. Each represents a situation where social costs/benefits differ from private costs/benefits.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.3.2', 'Externalities', 'Externalities are third-party effects from production/consumption. Negative externalities (pollution, congestion) lead to overproduction/consumption. Positive externalities (education, vaccination) lead to underproduction/consumption. Diagrams show divergence between private and social costs/benefits, leading to welfare loss.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.3.3', 'Public Goods', 'Public goods have two characteristics: non-excludability (cannot prevent non-payers from consuming) and non-rivalry (one person''s consumption doesn''t reduce availability to others). Examples: street lighting, national defense. Free-rider problem leads to market failure and under-provision. Government must provide public goods.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.3.4', 'Information Gaps', 'Imperfect information occurs when economic agents lack complete information. Asymmetric information exists when one party has more information than another (e.g., used car market - "lemons problem"). This leads to market failure, adverse selection, and moral hazard. Government intervention may be needed to provide information or regulate.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.4.1', 'Government Intervention in Markets', 'Government intervenes to correct market failure through: indirect taxes (to reduce negative externalities), subsidies (to increase positive externalities), maximum/minimum prices, trade pollution permits, state provision, regulation, and information provision. Each policy has advantages, disadvantages, and potential for government failure.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '1.4.2', 'Government Failure', 'Government failure occurs when intervention leads to a net welfare loss. Causes include: distortion of price signals, unintended consequences, excessive administrative costs, information gaps (government doesn''t have perfect information), lack of incentives in public sector. Examples: minimum wage causing unemployment, rent controls causing housing shortages.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Economics Theme 2 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '2.1.1', 'Economic Growth', 'Economic growth is the increase in real GDP over time. Measured by % change in real GDP. Actual growth is increase in real output. Potential growth is increase in productive capacity. Benefits: higher living standards, employment, tax revenue. Costs: inflation, inequality, environmental damage. Output gap is difference between actual and potential GDP.'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '2.1.2', 'Inflation', 'Inflation is sustained increase in general price level. Measured by CPI (Consumer Price Index) and RPI (Retail Price Index). Causes: demand-pull (excess demand), cost-push (rising costs). Effects: redistribution of income, reduced purchasing power, uncertainty, loss of international competitiveness. Deflation (falling prices) can cause recession.'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '2.1.3', 'Employment and Unemployment', 'Unemployment is when people actively seeking work cannot find jobs. Types: structural (skills mismatch), frictional (between jobs), seasonal (time of year), cyclical (recession). Measured by Claimant Count and Labour Force Survey. Costs: lost output, fiscal costs, social costs. Natural rate of unemployment includes structural and frictional.'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '2.1.4', 'Balance of Payments', 'Balance of Payments records all transactions between UK and rest of world. Current Account includes: trade in goods, trade in services, investment income, transfers. Capital Account: capital transfers. Financial Account: FDI, portfolio investment. Current account deficit means imports exceed exports. Can be financed by capital/financial inflows or using foreign reserves.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Economics Theme 3 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '3.1.1', 'Growth of Firms', 'Firms grow through internal growth (increasing output/market share) or external growth (mergers/takeovers). Types of integration: horizontal (same industry, same stage), vertical (same industry, different stage - forward/backward), conglomerate (different industries). Reasons: economies of scale, market power, diversification.'),
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '3.1.2', 'Demergers', 'Demergers involve breaking up firms. Reasons: diseconomies of scale, focus on core business, raise finance, regulatory pressure. Can increase efficiency and shareholder value but may lose economies of scale.'),
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '3.1.3', 'Profit', 'Types of profit: normal profit (minimum needed to stay in business - opportunity cost), supernormal/abnormal profit (above normal profit), subnormal profit (below normal - loss). Profit maximization occurs at MC=MR. Alternative objectives: revenue maximization, sales maximization, satisficing, corporate social responsibility.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Economics Theme 4 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '4.1.1', 'Globalisation', 'Globalisation is increasing integration of world economies. Causes: reduced transport costs, technology, trade liberalization, MNCs. Benefits: lower prices, choice, efficiency, growth. Costs: structural unemployment, inequality, loss of culture, environmental damage, tax avoidance by MNCs.'),
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '4.1.2', 'Specialisation and Trade', 'Absolute advantage: country can produce more with given resources. Comparative advantage: country has lower opportunity cost. Countries should specialize according to comparative advantage. Benefits of trade: higher output, lower prices, choice, economies of scale. Limitations: transport costs, trade barriers, assumptions unrealistic.'),
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '4.1.3', 'Pattern of Trade', 'Factors affecting trade patterns: comparative advantage, emerging economies, trading blocs, changes in exchange rates. UK imports: manufactured goods, oil. UK exports: services (financial), manufactured goods. Trade deficit in goods, surplus in services.'),
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'ECON')), '4.1.4', 'Terms of Trade', 'Terms of trade = Index of export prices / Index of import prices × 100. Improvement means exports more expensive relative to imports. Caused by: increased demand for exports, reduced supply of exports, appreciation. Impact depends on PED for exports/imports.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;
