-- Business Theme 1 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.1.1', 'The Market', 'A market is where buyers and sellers interact to exchange goods/services. Types: mass market (large scale, standardized), niche market (small, specialized). Market size measured by volume (units sold) or value (revenue). Market share = company sales / total market sales × 100. Dynamic markets constantly change due to innovation, competition, economic factors.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.1.2', 'Market Research', 'Market research gathers information about customers, competitors, markets. Primary research: first-hand data (surveys, questionnaires, focus groups, observation). Secondary research: existing data (government statistics, market reports). Qualitative: opinions, feelings. Quantitative: numerical data. Sampling methods affect reliability and cost.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.1.3', 'Market Positioning', 'Market positioning defines how product is perceived relative to competitors. Market mapping shows position on two dimensions (e.g., price vs quality). USP (Unique Selling Point) differentiates product. Competitive advantage achieved through differentiation or cost leadership. Positioning must match target market needs.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.2.1', 'Product and Service Design', 'Design mix balances: function (fitness for purpose), aesthetics (appearance), cost (affordability). Product design affects: differentiation, brand image, production costs, sustainability. Services focus on customer experience. Design must consider target market, technology, environmental impact. Product development process: idea generation, screening, development, testing, launch.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.2.2', 'Branding and Promotion', 'Brand is name, symbol, design identifying products. Strong brands create: customer loyalty, price premium, differentiation. Brand value measured financially. Promotion: advertising, sales promotion, public relations, sponsorship, digital marketing. Promotional mix depends on: target market, budget, product, competition, market size. Integrated marketing uses multiple channels.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.2.3', 'Pricing Strategies', 'Pricing strategies: cost-plus (cost + markup), competitive (match/undercut rivals), penetration (low price to gain share), skimming (high initial price), predatory (below cost to eliminate competition), psychological (£9.99). Price elasticity affects revenue. Factors: costs, competition, brand strength, stage in product life cycle.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.2.4', 'Distribution', 'Distribution channels: direct (producer to consumer), indirect (intermediaries involved). Retailers: sell to consumers. Wholesalers: buy bulk, sell to retailers. E-commerce enables direct distribution. Channel choice depends on: product type, target market, cost, control needed, geographical coverage. Multi-channel retailing uses various routes.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.2.5', 'Product Life Cycle', 'Stages: Development (high costs, no sales), Introduction (slow sales growth), Growth (rapid sales increase), Maturity (peak sales, stable), Decline (falling sales). Extension strategies: new markets, product modification, new uses, repositioning. Marketing mix changes at each stage. Not all products follow pattern - some have short/long cycles.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.3.1', 'Approaches to Staffing', 'Recruitment: internal (promotion, transfers - motivating, cheaper) or external (wider choice, new ideas). Selection methods: interviews, tests, assessment centers. Training: induction (new employees), on-the-job (learning while working), off-the-job (courses). Workforce planning ensures right people, right place, right time.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.3.2', 'Organizational Design', 'Organizational structure shows hierarchy and reporting relationships. Types: hierarchical (tall - many layers, narrow span), flat (few layers, wide span). Centralized: decisions at top. Decentralized: decisions delegated. Matrix structure: project-based teams. Structure affects: communication, motivation, flexibility, costs.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.3.3', 'Motivation', 'Taylor: Scientific management - pay motivates. Maslow: Hierarchy of needs - physiological, safety, social, esteem, self-actualization. Herzberg: Two-factor theory - hygiene factors (prevent dissatisfaction), motivators (create satisfaction). Mayo: Human relations - social factors important. Financial motivation: salary, bonuses, commission, profit share. Non-financial: empowerment, teamwork, job enrichment.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '1.3.4', 'Leadership', 'Leadership styles: Autocratic (leader decides - quick decisions, demotivating), Democratic (consultation - motivating, slower), Laissez-faire (minimal interference - for skilled workers, lack of direction). Tannenbaum-Schmidt continuum shows range. Style depends on: task urgency, worker skills, leader personality, organizational culture.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Business Theme 2 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '2.1.1', 'Internal Sources of Finance', 'Retained profit: profit kept in business - cheap, no interest, limited amount. Sale of assets: sell unused assets - generates cash, lose future income. Owner''s capital: entrepreneurs invest own money. Share capital: sell shares - permanent capital, dilutes control. Advantages: no interest, flexible. Disadvantages: limited availability.'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '2.1.2', 'External Sources of Finance', 'Loan capital: borrowing - interest payments, secured on assets. Overdrafts: flexible, short-term, high interest. Trade credit: delayed payment to suppliers. Leasing: hire equipment, no large capital outlay. Venture capital: equity finance for high-growth startups - large amounts, lose control. Crowdfunding: raise small amounts from many people.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Business Theme 3 Topics  
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '3.1.1', 'Corporate Objectives', 'Corporate objectives are medium/long-term goals. Examples: profit maximization, growth, market share, survival, corporate social responsibility, customer satisfaction. SMART objectives: Specific, Measurable, Achievable, Relevant, Time-bound. Mission statement defines purpose. Vision describes aspiration. Objectives cascade down organization.'),
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '3.1.2', 'Business Strategies', 'Strategies are plans to achieve objectives. Ansoff Matrix: market penetration, market development, product development, diversification. Porter''s Generic Strategies: cost leadership, differentiation, focus. SWOT analysis: Strengths, Weaknesses, Opportunities, Threats. Strategy must fit resources, environment, stakeholder expectations.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Business Theme 4 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '4.1.1', 'Globalisation', 'Globalisation increases international business integration. Impacts businesses: larger markets, more competition, complex supply chains, cultural challenges. Opportunities: access to resources, economies of scale, risk spreading. Threats: competition from low-cost countries, exchange rate risk, political instability.'),
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'BUS')), '4.1.2', 'Conditions for Trading Internationally', 'Factors enabling international trade: trade agreements, technology, transport infrastructure, common currencies, political stability. Barriers: tariffs, quotas, regulations, cultural differences, exchange rates. Trading blocs (EU, NAFTA) reduce barriers between members. MNCs operate in multiple countries.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;
