-- Politics Theme 1 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.1.1', 'Democracy and Participation', 'Democracy: rule by the people. Direct democracy: people vote on every issue (referendums). Representative democracy: elect representatives to make decisions (MPs). UK is parliamentary democracy with constitutional monarchy. Franchise extended over time: 1918 (some women), 1928 (all women), 1969 (voting age to 18). Participation: voting, joining parties, pressure groups, protests.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.1.2', 'Political Parties', 'Main parties: Conservative, Labour, Liberal Democrats. Party functions: representation, participation, candidate recruitment, policy formulation, government formation. Party systems: two-party (UK traditionally), multi-party. Left-right spectrum: economic policy (state intervention vs free market). Consensus and adversary politics. Party funding: membership fees, donations, state funding debate.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.1.3', 'Electoral Systems', 'First Past The Post (FPTP): UK general elections - simple, strong government, unrepresentational. Proportional Representation: more proportional, coalition governments. Additional Member System (AMS): Scottish Parliament, Welsh Assembly. Single Transferable Vote (STV): Northern Ireland Assembly. Supplementary Vote (SV): London Mayor. Each system has trade-offs between proportionality, simplicity, constituency link.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.1.4', 'Voting Behaviour and the Media', 'Voting behaviour influenced by: social class (traditionally strong), age, gender, ethnicity, region. Class dealignment and partisan dealignment reduce predictability. Valence issues: competence on issues all agree on. Rational choice theory: voters choose party offering most benefit. Media influences: agenda-setting, framing, bias allegations. Social media impact growing.'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.2.1', 'Liberalism', 'Core values: individual freedom, tolerance, reason, equality of opportunity, limited government, consent. Classical liberalism: minimal state, free markets, negative freedom. Modern liberalism: more state intervention, positive freedom, welfare state. Key thinkers: John Locke (natural rights), John Stuart Mill (harm principle), John Rawls (social justice).'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.2.2', 'Conservatism', 'Core values: tradition, pragmatism, human imperfection, organic society, property, authority. Traditional conservatism: paternalism, one nation. New Right: neo-liberalism (free markets) and neo-conservatism (strong state, traditional values). Key thinkers: Edmund Burke (tradition, change to conserve), Ayn Rand (objectivism), Robert Nozick (minimal state).'),
((SELECT id FROM public.themes WHERE theme_number = 1 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '1.2.3', 'Socialism', 'Core values: equality, collectivism, class, workers control, common ownership. Revolutionary socialism: Marx - overthrow capitalism, dictatorship of proletariat. Social democracy: evolutionary socialism, mixed economy, welfare state, redistribution. Third Way: combines market efficiency with social justice. Key thinkers: Karl Marx, Beatrice Webb (Fabian), Anthony Crosland (revisionism).')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Politics Theme 2 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '2.1.1', 'The Constitution', 'Constitution: rules governing politics. UK: uncodified (no single document), unentrenched (can change easily), flexible. Sources: statute law, common law, conventions, authoritative works, EU law (historically), treaties. Parliamentary sovereignty: Parliament is supreme law-maker. Rule of law: everyone equal before law. Recent reforms: devolution (1998), Human Rights Act (1998), Supreme Court (2009).'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '2.1.2', 'Parliament', 'Bicameral: House of Commons (elected, 650 MPs) and House of Lords (appointed/hereditary, ~800 members). Functions: legislation, scrutiny of government, representation, debate, legitimacy. Legislative process: first reading, second reading, committee stage, report stage, third reading, Lords stages, Royal Assent. Lords can delay but not block Commons. Select committees scrutinize government departments.'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '2.1.3', 'Prime Minister and Executive', 'Prime Minister: head of government, appoints Cabinet, chairs Cabinet, controls Parliament, represents UK internationally. Cabinet: senior ministers, collective responsibility, discuss/decide policy. Sources of PM power: prerogative powers, patronage, party leadership, media focus. Constraints: Parliament, Cabinet, party, media, events. Presidential tendencies: Blair, Thatcher - dominant PMs.'),
((SELECT id FROM public.themes WHERE theme_number = 2 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '2.1.4', 'Relations Between Institutions', 'Separation of powers: executive, legislature, judiciary separate to prevent tyranny. UK: fusion of executive and legislature (PM in Commons). Checks and balances: Parliament checks executive through votes, questions, committees. Judiciary independent but Parliament sovereign. European Convention on Human Rights (ECHR) allows judicial review of legislation for compatibility.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Politics Theme 3 Topics (US Politics)
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '3.1.1', 'The US Constitution and Federalism', 'US Constitution: codified (written document), entrenched (hard to amend - 2/3 Congress, 3/4 states), separation of powers, checks and balances, Bill of Rights (first 10 amendments). Federalism: power divided between federal government and states. Enumerated powers (federal), reserved powers (states), concurrent powers (shared). Debates over federal vs state power continue.'),
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '3.1.2', 'US Congress', 'Bicameral: House of Representatives (435 members, 2-year terms, represent districts) and Senate (100 members, 6-year terms, represent states). Functions: legislation, oversight, representation, constitutional amendments. Legislative process: committee stage crucial. Filibuster in Senate (can block legislation). Congress powerful but gridlock common, especially with divided government.'),
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '3.1.3', 'US Presidency', 'President: head of state and government, 4-year term, max 2 terms. Powers: commander-in-chief, foreign policy, veto legislation, appoint judges/officials, executive orders. Limits: Congress checks (legislation, budget, treaties, appointments), judiciary (judicial review), federalism. Imperial vs imperiled presidency debate. Modern presidents use media, executive orders to increase power.'),
((SELECT id FROM public.themes WHERE theme_number = 3 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '3.1.4', 'US Supreme Court', 'Nine justices, lifetime appointments, interpret Constitution. Judicial review: can strike down laws/actions as unconstitutional (Marbury v Madison 1803). Political impact: abortion (Roe v Wade), civil rights, gun control. Judicial activism vs restraint debate. Appointment process politicized. Protects rights but unelected.')
ON CONFLICT (theme_id, topic_code) DO NOTHING;

-- Politics Theme 4 Topics
INSERT INTO public.topics (theme_id, topic_code, title, content) VALUES
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '4.1.1', 'Nationalism', 'Nationalism: belief in nation as natural political community. Liberal nationalism: self-determination, inclusive, progressive. Conservative nationalism: traditional, exclusive, protectionist. Expansionist nationalism: aggressive, imperialism. Post-colonial nationalism: independence movements. Can unite or divide. Recent resurgence: Brexit, Scottish independence, populism.'),
((SELECT id FROM public.themes WHERE theme_number = 4 AND subject_id = (SELECT id FROM public.subjects WHERE code = 'POL')), '4.1.2', 'Multiculturalism', 'Multiculturalism: recognizing/celebrating diversity. Liberal multiculturalism: tolerance, integration. Pluralist multiculturalism: separate communities. Cosmopolitanism: shared humanity transcends cultures. Debates: integration vs segregation, shared values vs diversity, national identity. Criticism: undermines social cohesion, challenges equality (gender, LGBTQ+ rights).')
ON CONFLICT (theme_id, topic_code) DO NOTHING;
